server:
  port: 10002
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/taccisum/spring-cloud-test-config-center.git
#          如果需要认证，通过以下两项配置
#          如果使用ssh，则需要在~/.ssh中存储私钥文件（或者使用yml配置）
#          username:
#          password:
          clone-on-start: true
#          force-pull: true # 本地仓库内容被修改导致无法pull时，可以启用force pull来解决这个问题
