spring:
  application:
    name: simple-client
# 禁用自动注册
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false
eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
     defaultZone: http://tac.eureka.com:10001/eureka/ #注册中心url，如果是部署在内网，一般通过修改hosts文件与ip进行解耦
server:
  port: 20001
